TechnicalSupport/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static


from ordermanager import urls

urlpatterns = [
     # Redirect / to WebPagRuedaDLV
    url(r'^$', RedirectView.as_view(url='ordermanager/'), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^ordermanager/', include(urls, namespace='ordermanager'))
]

handler404 = 'ordermanager.views.error_404_view'

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordermanager/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    
    # Auth Urls
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/ordermanager/login/'}, name='logout'),

    # App views    
   	url(r'^$', views.principal, name='principal'),
   	url(r'^create-Order/(?P<int>[0-9]+)/$', views.createOrder, name='createOrder'),
   	url(r'^request-dashboard/$', views.dashboard, name='dashboard'),
    url(r'^department-dashboard/$', views.department_dashboard, name='department_dashboard'),
    url(r'^request-type-dashboard/$', views.request_type_dashboard, name='request_type_dashboard'),
   	url(r'^order-Pending/$', views.orderPending, name='orderPending'),
   	url(r'^order-Support/(?P<pk>[0-9]+)/$', views.orderSupport, name='orderSupport'),
   	url(r'^poll/(?P<pk>[0-9]+)/$', views.poll, name='poll'),
    url(r'^comment/$', views.comment, name='comment'), 
    url(r'^order-Cancel/(?P<pk>[0-9]+)/$', views.orderCancel, name='orderCancel'),
    url(r'^order-Pause/(?P<pk>[0-9]+)/$', views.orderPause, name='orderPause'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^Create-Maintenance/$', views.CreateMaintenance, name='CreateMaintenance'),
    url(r'^Order-Observations/$', views.OrderObservations, name='OrderObservations'),
    url(r'^order-Show/(?P<pk>[0-9]+)/$', views.orderShow, name='orderShow'),
    url(r'^Maintenance-Support/(?P<pk>[0-9]+)/$', views.MaintenanceSupport, name='MaintenanceSupport'),
    url(r'^Maintenance-Cancel/(?P<pk>[0-9]+)/$', views.MaintenanceCancel, name='MaintenanceCancel'),
    url(r'^Maintenance-Pause/(?P<pk>[0-9]+)/$', views.MaintenancePause, name='MaintenancePause'),
    url(r'^Maintenance-Show/(?P<pk>[0-9]+)/$', views.MaintenanceShow, name='MaintenanceShow'),
    url(r'^Poll-satisfaction/$', views.Poll_satisfaction, name='Poll_satisfaction'),
    url(r'^Change-password/$', views.change_password, name='change_password'),
]

ordermanager/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from os import path

from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver


def unique_file_path(instance, filename):
    base, ext = path.splitext(filename)
    newname = "%s%s" % (instance.name, ext)
    return path.join('equipment_img', newname)


# Create your models here.
class Equipment(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    location = models.CharField(max_length=200, null=False, blank=False)
    responsible = models.ForeignKey(
        User, null=False, blank=False, related_name='equipment_user_set', on_delete=models.PROTECT
    )
    image = models.ImageField(upload_to=unique_file_path, null=True, blank=False)
    inventory_type = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Computer equipment'),
            ('2', 'Audio'),
            ('3', 'Video'),
            ('4', 'Cabling')
        )
    )

    def __str__(self):
        return 'Equipment: {0} '.format(self.name)


class Request(models.Model):
    user = models.ForeignKey(
        User, null=False, blank=False, related_name='request_user_set', on_delete=models.PROTECT
    )
    technical = models.ForeignKey(
        User, null=True, blank=True, related_name='request_technical_set', on_delete=models.PROTECT
    )
    request_type = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Maintenance of computer equipment'),
            ('2', 'Configuration in general'),
            ('3', 'Software installation'),
            ('4', 'Computer consulting'),
            ('5', 'Audio and Events'),
            ('6', 'Problems in general'),
            ('7', 'Problems in Laboratories'),
        )
    )
    equipment_id = models.ForeignKey(
        Equipment, null=True, blank=True, related_name='equipment_set', on_delete=models.PROTECT
    )
    status = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Pennding'),
            ('2', 'on process'),
            ('3', 'Canceled'),
            ('4', 'Done'),
            ('5', 'Pause')
        )
    )
    comments = models.CharField(max_length=200, null=True, blank=False)
    observations = models.CharField(max_length=200, null=True, blank=False)
    date_request = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    date_onprocess = models.DateTimeField(null=True, blank=True)
    date_done = models.DateTimeField(null=True, blank=True)
    date_cancel = models.DateTimeField(null=True, blank=True)
    date_pause = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return 'Request N: {0} Status: {1} Request type: {2}'.format(self.id, self.get_status_display(),
                                                                     self.get_request_type_display())


class Poll(models.Model):
    question = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Was it easy to request the service?'),
        )
    )
    answer = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Very satisfied'),
            ('2', 'Satisfied'),
            ('3', 'Unsatisfied'),
            ('4', 'Very Unsatisfied'),
        )
    )
    questionTwo = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'What was the quality of the service?'),
        )
    )
    answerTwo = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Very satisfied'),
            ('2', 'Satisfied'),
            ('3', 'Unsatisfied'),
            ('4', 'Very Unsatisfied'),
        )
    )
    questionThree = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'How do you feel about the behavior of the technician?'),
        )
    )
    answerThree = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Very satisfied'),
            ('2', 'Satisfied'),
            ('3', 'Unsatisfied'),
            ('4', 'Very Unsatisfied'),
        )
    )
    questionFour = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'How do you feel about the service the technician performed?'),
        )
    )
    answerFour = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Very satisfied'),
            ('2', 'Satisfied'),
            ('3', 'Unsatisfied'),
            ('4', 'Very Unsatisfied'),
        )
    )
    questionFive = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'What is your level of satisfaction?'),
        )
    )
    answerFive = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Very satisfied'),
            ('2', 'Satisfied'),
            ('3', 'Unsatisfied'),
            ('4', 'Very Unsatisfied'),
        )
    )
    request_id = models.ForeignKey(
        Request, null=False, blank=True, related_name='request_set', on_delete=models.PROTECT
    )
    date_request = models.DateTimeField(null=True, blank=False, auto_now_add=True)

    status = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Pennding'),
            ('2', 'Done'),
        )
    )

    def __str__(self):
        return 'Poll of the {0} '.format(self.request_id)


class Activity(models.Model):
    tittle = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    date_request = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    date_event = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return 'Tittle: {0} '.format(self.tittle)


class Comment(models.Model):
    comment = models.CharField(max_length=200, null=False, blank=False)
    user = models.ForeignKey(
        User, null=False, blank=False, related_name='comment_user_set', on_delete=models.PROTECT
    )
    date_request = models.DateTimeField(null=True, blank=False, auto_now_add=True)

    def __str__(self):
        return 'Comment by: {0} '.format(self.user.get_full_name)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    department = models.CharField(
        max_length=1, blank=False, default='5', choices=(
            ('1', 'Principal'),
            ('2', 'Administration and finance'),
            ('3', 'Linking'),
            ('4', 'Planning and evaluation'),
            ('5', 'Academician'),
        )
    )
    building = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Teaching 1'),
            ('2', 'Teaching 2'),
            ('3', 'Heavy Laboratory'),
            ('4', 'Library'),
            ('5', 'Other'),
        )
    )

    def __str__(self):  # __unicode__ for Python 2

        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Preventive_Maintenance(models.Model):
    user = models.ForeignKey(
        User, null=False, blank=False, related_name='Maintenance_user_set', on_delete=models.PROTECT
    )
    technical = models.ForeignKey(
        User, null=True, blank=True, related_name='Maintenance_technical_set', on_delete=models.PROTECT
    )
    request_type = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Preventive Maintenance'),
            ('2', 'Corrective Maintenance')
        )
    )
    status = models.CharField(
        max_length=1, blank=False, default='1', choices=(
            ('1', 'Pennding'),
            ('2', 'on process'),
            ('3', 'Canceled'),
            ('4', 'Done'),
            ('5', 'Pause')
        )
    )
    comments = models.CharField(max_length=200, null=True, blank=False)
    observations = models.CharField(max_length=200, null=True, blank=False)
    date_request = models.DateTimeField(null=False, blank=False, auto_now_add=True)
    date_onprocess = models.DateTimeField(null=True, blank=True)
    date_done = models.DateTimeField(null=True, blank=True)
    date_cancel = models.DateTimeField(null=True, blank=True)
    date_pause = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return 'Maintenance N: {0} Status: {1} Request type: {2}'.format(self.id, self.get_status_display(),
                                                                     self.get_request_type_display())


class Equipment_Maintenance(models.Model):
    equipment_id = models.ForeignKey(
        Equipment, null=True, blank=True, related_name='maintenance_equipment_set', on_delete=models.PROTECT
    )
    preventive_maintenance_id = models.ForeignKey(
        Preventive_Maintenance, null=True, blank=True, related_name='preventive_maintenance_set', on_delete=models.PROTECT
    )

ordermanager/templates/comment.html
{% extends 'base.html' %}
{% load static %}
<!-- Estructura basica para diseño -->

{% block 'main' %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Comments! <small>See us what was yout expirience in our web application!</small></h2>
          <ul class="nav navbar-right panel_toolbox">
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form action="{% url 'ordermanager:comment'  %}" method="post" class="form-horizontal form-label-left">
            {% csrf_token %}            
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Comment<span class="required"></span>
              </label>
              <div class="col-md-9 col-sm-9 col-xs-12">
                <textarea name="comments" class="form-control" rows="3" placeholder='See us what is your opinion about the webapplication.'></textarea>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <a type="button" class="btn btn-danger" href="{% url 'ordermanager:principal' %}">Cancel</a>
                <button type="reset" class="btn btn-primary">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}                

ordermanager/templates/order_show.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block 'main' %}
    <div class="right_col" role="main">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Every information about
                            <strong>the order #{{ principal_request.id }} </strong></h2>
                        <ul class="nav navbar-right panel_toolbox">
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br/>

                        <form action="{% url 'ordermanager:orderSupport' principal_request.pk %}" method="post"
                              class="form-horizontal form-label-left">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">ID:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.id }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">User:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.user.get_full_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Technical:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.technical.get_full_name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Deparment:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.user.profile.get_department_display }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Building:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.user.profile.get_building_display }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Request type:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.get_request_type_display }}">
                                </div>
                            </div>
                            {% if principal_request.equipment_id %}
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12">Equipment:</label>

                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <input type="text" class="form-control" readonly="readonly"
                                               placeholder="{{ principal_request.equipment_id }}">
                                    </div>
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Problem:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <textarea type="text" class="form-control" rows="4" readonly="readonly"
                                              placeholder="{{ principal_request.comments }}"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Date create:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.date_request|date:"D d M Y" }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Date on proccess:</label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <input type="text" class="form-control" readonly="readonly"
                                           placeholder="{{ principal_request.date_onprocess|date:"D d M Y" }}">
                                </div>
                            </div>
                            {% if principal_request.status == '3' %}
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12">Date Canceled:</label>

                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <input type="text" class="form-control" readonly="readonly"
                                               placeholder="{{ principal_request.date_cancel|date:"D d M Y" }}">
                                    </div>
                                </div>
                            {% elif principal_request.status == '4' %}
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12">Date Done:</label>

                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <input type="text" class="form-control" readonly="readonly"
                                               placeholder="{{ principal_request.date_done|date:"D d M Y" }}">
                                    </div>
                                </div>
                            {% elif principal_request.status == '5' %}
                                <div class="form-group">
                                    <label class="control-label col-md-4 col-sm-4 col-xs-12">Date on pause:</label>

                                    <div class="col-md-4 col-sm-4 col-xs-12">
                                        <input type="text" class="form-control" readonly="readonly"
                                               placeholder="{{ principal_request.date_pause|date:"D d M Y" }}">
                                    </div>
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <label class="control-label col-md-4 col-sm-4 col-xs-12">Observations:<span
                                        class="required"></span>
                                </label>

                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <textarea name="observations" class="form-control" rows="4"
                                              readonly="readonly">{{ principal_request.observations }}</textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-4">
                                    <a type="button" class="btn btn-primary"
                                       {% if user.groups.last.name == 'Technical' or user.groups.last.name == 'Manager' %}
                                       href="{% url 'ordermanager:OrderObservations' %}" {% else %}
                                       href="{% url 'ordermanager:principal' %}"
                                       {% endif %}
                                            >Return</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}                

ordermanager/templates/poll.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block 'main' %}
<div class="right_col" role="main">
  <div class="row">
  	<div class="col-md-12 col-xs-12">
  		<div class="x_panel">
  			<div class="x_title">
  				<h2>You are doing the poll from the {{ poll.request_id }}</h2>
  				<ul class="nav navbar-right panel_toolbox">
  					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
  					</li>
  					<li><a class="close-link"><i class="fa fa-close"></i></a>
  					</li>
  				</ul>
  				<div class="clearfix"></div>
  			</div>
  			<div class="x_content">
  				<br />
  				<form class="form-horizontal" method="post">
            		{% csrf_token %}
  					<div class="form-group">
  						<div>
  							<div class="col-md-12">
  								<h3> {{ poll.get_question_display }} </h3>
  							</div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="1" checked name="answer"> Very satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="2" name="answer"> Satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="3"  name="answer"> Unsatisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="4"  name="answer"> Very Unsatisfied
  								</label>
  							</div>
  						</div>
  					</div>
  					<div class="ln_solid"></div>
  					<div class="form-group">
  						<div>
  							<div class="col-md-12">
  								<h3> {{ poll.get_questionTwo_display }} </h3>
  							</div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" checked value="1"  name="answerTwo"> Very satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="2" name="answerTwo"> Satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="3" name="answerTwo"> Unsatisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="4" name="answerTwo"> Very Unsatisfied
  								</label>
  							</div>
  						</div>
  					</div>
  					<div class="ln_solid"></div>  					
  					<div class="form-group">
  						<div>
  							<div class="col-md-12">
  								<h3> {{ poll.get_questionThree_display }} </h3>
  							</div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" checked value="1" name="answerThree"> Very satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="2" name="answerThree"> Satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat"  value="3" name="answerThree"> Unsatisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="4" name="answerThree"> Very Unsatisfied
  								</label>
  							</div>
  						</div>
  					</div>
  					<div class="ln_solid"></div>
  					<div class="form-group">
  						<div>
  							<div class="col-md-12">
  								<h3> {{ poll.get_questionFour_display }} </h3>
  							</div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" checked value="1" name="answerFour"> Very satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="2" name="answerFour"> Satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="3" name="answerFour"> Unsatisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="4" name="answerFour"> Very Unsatisfied
  								</label>
  							</div>
  						</div>
  					</div>
  					<div class="ln_solid"></div>
  					<div class="form-group">
  						<div>
  							<div class="col-md-12">
  								<h3> {{ poll.get_questionFive_display }} </h3>
  							</div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" checked value="1" name="answerFive"> Very satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="2" name="answerFive"> Satisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="3" name="answerFive"> Unsatisfied
  								</label>
  							</div>
  						</div>
  						<div>
  							<div class="col-md-3 col-sm-3 col-xs-3" class="radio">
  								<label>
  									<input type="radio" class="flat" value="4" name="answerFive"> Very Unsatisfied
  								</label>
  							</div>
  						</div>
  					</div>
  					<div class="ln_solid"></div>  					
  					<div class="form-group">
  						<div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
  							<a type="button" href="{% url 'ordermanager:principal' %}" class="btn btn-primary">Cancel</a>
  							<button type="submit" class="btn btn-success">Submit</button>
  						</div>
  					</div>

  				</form>
  			</div>
  		</div>
  	</div>
  </div>
</div>
{% endblock %}                